# Generated by Django 5.1.3 on 2024-11-17 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('activity_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('duration_seconds', models.IntegerField()),
                ('avg_power_watts', models.FloatField()),
                ('avg_speed_mps', models.FloatField()),
                ('elevation_gain_m', models.FloatField()),
                ('start_lat', models.FloatField()),
                ('start_lng', models.FloatField()),
                ('end_lat', models.FloatField()),
                ('end_lng', models.FloatField()),
                ('gps_data', models.JSONField()),
                ('calories', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=255)),
                ('salt', models.CharField(max_length=255)),
                ('strava_athlete_id', models.IntegerField()),
                ('strava_refresh_token', models.CharField(max_length=255)),
                ('strava_access_token', models.CharField(max_length=255)),
                ('strava_token_expires_at', models.DateTimeField()),
                ('strava_connected_at', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('current_xp', models.IntegerField()),
                ('current_level', models.IntegerField()),
                ('distance_biked_km', models.FloatField()),
                ('distance_run_km', models.FloatField()),
                ('distance_swam_km', models.FloatField()),
                ('distance_walked_km', models.FloatField()),
                ('distance_hiked_km', models.FloatField()),
                ('createxd_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
