# Generated by Django 5.1.3 on 2024-11-17 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_user_profile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='last_name',
        ),
    ]
